/*
** EPITECH PROJECT, 2022
** Enum
** File description:
** Enum
*/

#pragma once
#include <chrono>

#define NB_MAX_PLAYERS_PER_ROOM 4
#define ROOM_ID_SIZE 8
#define DISCONNECTION_TIME 1500
#define SPACESHIP_SPEED 300

namespace ecs
{
    enum Scenes { ROOM1, GAME1, ROOM2, GAME2, ROOM3, GAME3,
                PUBLICROOM, PRIVATEROOM, LISTROOM, JOINROOMBYID, QUITROOM,
                MENU, SETTINGS, WIN, LOOSE, GAME, RETURNTOGAME, TYPEPSEUDO, HOWTOPLAY, ACHIEVEMENTS };

    enum EntityTypes { SPACESHIP, MONSTER, CAVE_MONSTER, ICE_MONSTER, FIRE_MONSTER, DESERT_MONSTER, FOREST_MONSTER, BASIC_MONSTER, BOSS_FIRE_SPACESHIP, BOSS_DESERT_WORMS, BOSS_ICE_HEADESTROYER, BOSS_CAVERN_MAGICIAN, BOSS_FOREST_RED, BOSS_FOREST_GREEN, BOSS_FOREST_BLUE, SHOT, BASIC_SHOT, RED_SHOT, BLUE_SHOT, GREEN_SHOT, SPACESHIP_SHOT, WORMS_SHOT, HEAD_SHOT, SHOT, BUTTON, WALL, BACKGROUND, PARALLAX, ROOM, ROOMID, ROOMMODE, ROOMPLAYERSNAME, SHAPE, TEXT, TEXTBOX, TEXTBOXNUMBER, PSEUDO, MUSIC, SFX };
    enum AchievementTypes { MATRIX, RAMPAGE, HACKER, NEMESIS, BFF, WORLDWARRIOR, PAIN, MARVIN };
    class Enum {
        public:
            static std::chrono::time_point<std::chrono::system_clock> ping_latency;
            static int ping_latency_ms;
    };
} // namespace ecs
